site_name: Qleet User Documentation
site_author: Qleet.io
repo_url: https://github.com/qleet/user-docs
repo_name: qleet/user-docs
edit_uri: blob/main/docs/
nav:
  - Qleet: index.md
  - Getting Started: getting-started.md
  - FAQ: faq.md
  - Guides:
    - Install qleetctl: guides/install-qleetctl.md
    - Qleet Account: guides/qleet-account.md
    - Qleet Authentication: guides/qleet-authentication.md
    - Qleet User: guides/qleet-user.md
    - Qleet RBAC: guides/qleet-rbac.md
    - Control Plane: guides/qleet-control-plane.md
    - Add AWS Account: guides/add-aws-account.md
  - Threeport:
      - Threeport: threeport/index.md
      - FAQ: threeport/faq.md
      - Concepts:
          - Application Orchestration: threeport/concepts/application-orchestration.md
          - Orchestration Abstractions: threeport/concepts/orchestration-abstractions.md
          - Comparisons: threeport/concepts/comparisons.md
          - Definitions & Instances: threeport/concepts/definitions-instances.md
          - Extensions: threeport/concepts/extensions.md
      - Threeport Objects:
          - Kubernetes Runtimes:
              - Introduction: threeport/kubernetes-runtime/kubernetes-intro.md
              - Remote Kubernetes Runtime: threeport/kubernetes-runtime/remote-kubernetes-runtime.md
          - Workloads:
              - Introduction: threeport/workloads/workload-intro.md
              - Local Workload: threeport/workloads/deploy-workload-local.md
              - Remote Workload: threeport/workloads/deploy-workload-aws.md
              - Namespace Management: threeport/workloads/namespaces.md
          - Helm Workloads:
              - Introduction: threeport/helm-workloads/helm-intro.md
              - Local Helm Workload: threeport/helm-workloads/deploy-helm-local.md
          - AWS:
              - Introduction: threeport/aws/aws-intro.md
              - IAM Permissions: threeport/aws/aws-iam.md
              - Basic AWS Setup: threeport/aws/basic-aws-setup.md
              - Advanced AWS Setup: threeport/aws/advanced-aws-setup.md
          - Terraform:
              - Introduction: threeport/terraform/terraform-intro.md
              - AWS RDS Database: threeport/terraform/rds-database.md
          - Gateways:
              - Introduction: threeport/gateways/gateway-intro.md
          - Secrets:
              - Introduction: threeport/secrets/secrets-intro.md
          - Observability:
              - Introduction: threeport/observability/observability-intro.md
              - Local Observability: threeport/observability/deploy-observability-local.md
          - Control Planes:
              - Introduction: threeport/control-planes/control-plane-intro.md
      - SDK:
          - Introduction: threeport/sdk/sdk-intro.md
      - Architecture:
          - Overview: threeport/architecture/overview.md
          - Control Plane: threeport/architecture/control-plane.md
          - Threeport Controllers: threeport/architecture/threeport-controllers.md
          - Kubernetes Federation: threeport/architecture/kubernetes-federation.md
theme:
  favicon: img/favicon.ico
  features:
    - content.code.copy
  logo: img/logo.png
  name: material
  palette:
    - accent: indigo
      primary: indigo
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - accent: indigo
      primary: indigo
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/qleet
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
copyright: Copyright &copy; 2022-2024 Qleet.io
