site_name: Qleet User Documentation
site_author: Qleet.io
repo_url: https://github.com/qleet/user-docs
repo_name: qleet/user-docs
edit_uri: blob/main/docs/

nav:
  - Qleet: 'index.md'
  - Guides:
    - 'guides/install.md'

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
    - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/qleet

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

copyright: Copyright &copy; 2022-2023 Qleet.io
