site_name: Qleet User Documentation
site_author: Qleet.io
repo_url: https://github.com/qleet/user-docs
repo_name: qleet/user-docs
edit_uri: blob/main/docs/
nav:
  - Qleet: index.md
  - Guides:
      - guides/install.md
  - Threeport:
      - Threeport: threeport/index.md
      - Guides:
          - threeport/guides/remote-kubernetes-runtime.md
          - threeport/guides/deploy-workload-aws.md
          - threeport/guides/aws-iam.md
          - threeport/guides/aws-cross-account-access.md
          - threeport/guides/namespaces.md
      - Architecture:
          - Overview: threeport/architecture/overview.md
          - Tech Stack: threeport/architecture/tech-stack.md
          - Threeport Controllers: threeport/architecture/threeport-controllers.md
          - Kubernetes Federation: threeport/architecture/kubernetes-federation.md
          - Software Delivery: threeport/architecture/software-delivery.md
          - Orchestration Abstractions: threeport/architecture/orchestration-abstractions.md
theme:
  favicon: img/favicon.ico
  features:
    - content.code.copy
  logo: img/logo.png
  name: material
  palette:
    - accent: indigo
      primary: indigo
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - accent: indigo
      primary: indigo
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/qleet
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
copyright: Copyright &copy; 2022-2024 Qleet.io
