exclude:
  - docs/threeport/getting-started.md
  - docs/threeport/install/install-tptctl.md
  - docs/threeport/install/install-threeport-local.md
  - docs/threeport/install/install-threeport-aws.md
  - docs/threeport/deploy/deploy-workload-local.md
  - docs/threeport/managed-threeport.md

