name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-material-extensions mike
      - run: mkdocs gh-deploy --force
